// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrftdly307Nf5aX1TxWIWSzlTdjPS_SPA',
    appId: '1:71586977717:web:1bcc7eeb2a955d8de46bfc',
    messagingSenderId: '71586977717',
    projectId: 'crud-realtimedb',
    authDomain: 'crud-realtimedb.firebaseapp.com',
    databaseURL: 'https://crud-realtimedb-default-rtdb.firebaseio.com',
    storageBucket: 'crud-realtimedb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAELRFmCAq6rx-0rSr0QGFUaTQs3bZKV38',
    appId: '1:71586977717:android:92b0fa234338d48ee46bfc',
    messagingSenderId: '71586977717',
    projectId: 'crud-realtimedb',
    databaseURL: 'https://crud-realtimedb-default-rtdb.firebaseio.com',
    storageBucket: 'crud-realtimedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc85_-l2_9rMmka0fzG5LhZt2vIkdzOLI',
    appId: '1:71586977717:ios:9d5dd9e19ccf97e2e46bfc',
    messagingSenderId: '71586977717',
    projectId: 'crud-realtimedb',
    databaseURL: 'https://crud-realtimedb-default-rtdb.firebaseio.com',
    storageBucket: 'crud-realtimedb.appspot.com',
    androidClientId: '71586977717-cvvvetrosu9t796d5nnvtv1vfq1rakr7.apps.googleusercontent.com',
    iosClientId: '71586977717-8jodvsfcol75ga2ktf7fr8oumuerbkik.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudRealtimedb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc85_-l2_9rMmka0fzG5LhZt2vIkdzOLI',
    appId: '1:71586977717:ios:9d5dd9e19ccf97e2e46bfc',
    messagingSenderId: '71586977717',
    projectId: 'crud-realtimedb',
    databaseURL: 'https://crud-realtimedb-default-rtdb.firebaseio.com',
    storageBucket: 'crud-realtimedb.appspot.com',
    androidClientId: '71586977717-cvvvetrosu9t796d5nnvtv1vfq1rakr7.apps.googleusercontent.com',
    iosClientId: '71586977717-8jodvsfcol75ga2ktf7fr8oumuerbkik.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudRealtimedb',
  );
}
